vim.keymap.set('n', '<leader>w', '<cmd>w<cr>', { desc = '[W]rite', silent = true })
vim.keymap.set('n', '<leader>q', '<cmd>q<cr>', { desc = '[Q]uit', silent = true })

-- Center buffer while navigating
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-i>', '<C-i>zz')
vim.keymap.set('n', '<C-o>', '<C-o>zz')
vim.keymap.set('n', '{', '{zz')
vim.keymap.set('n', '}', '}zz')
vim.keymap.set('n', 'n', 'nzz')
vim.keymap.set('n', 'N', 'Nzz')
vim.keymap.set('n', 'gg', 'ggzz')
vim.keymap.set('n', 'G', 'Gzz')
vim.keymap.set('n', '%', '%zz')
vim.keymap.set('n', '*', '*zz') -- search current word forward
vim.keymap.set('n', '#', '#zz') -- search current word backward

-- telescope
vim.keymap.set('n', '<leader>?', require('telescope.buildin').oldfiles, { desc = '[?] Find recently open files' })
vim.keymap.set('n', '<leader>sb', require('telescope.buildin').buffers, { desc = '[S]earch open [B]uffers' })
vim.keymap.set('n', '<leader>sg', require('telescope.buildin').live_grep, { desc = '[S]earch by [G]rep' })
vim.keymap.set('n', '<leader>sh', require('telescope.buildin').help_tags, { desc = '[S]earch [H]elp' })
vim.keymap.set('n', '<leader>sf', function()
	require('telescope.buildin').find_files({ hidden = true })
end, { desc = '[S]earch [F]iles' })
vim.keymap.set('n', '<leader>sc', function()
	require('telescope.buildin').commands(require('telescope.themes').get_dropdown({ previewer = false }))
end, { desc = '[S]earch [C]ommand' })
vim.keymap.set('n', '<leader>/', function()
	require('telescope.buildin').current_buffer_fuzzy_find(require('telescope.themes').get_dropdown({ previewer = false }))
end, { desc = '[/] Fuzzily search in current buffer' })
vim.keymap.set('n', '<leader>ss', function()
	require('telescope.buildin').spell_suggest(require('telescope.themes').get_dropdown({ previewer = false }))
end, { desc = '[S]earch [S]pelling suggestions' })
